namespace: cdps-18

productpage:
  name: productpage-v1
  image: yagoferrara/practica_creativa2:productpage
  replicas: 1
  port: 9080
  serviceType: LoadBalancer

details:
  name: details-v1
  image: yagoferrara/practica_creativa2:details
  replicas: 4
  port: 7070

reviews:
  name: reviews-v3
  image: yagoferrara/practica_creativa2:reviews-v3
  replicas: 1
  port: 9080

ratings:
  name: ratings-v1
  image: yagoferrara/practica_creativa2:ratings
  replicas: 3
  port: 9080
